default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ubereats_development

test:
  <<: *default
  database: ubereats_test

production:
  <<: *default
  database: ubereats_production
  username: ubereats
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
